# Generated by Django 3.1.5 on 2021-01-28 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_id', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField()),
                ('level_of_task', models.IntegerField()),
                ('task', models.CharField(max_length=300)),
            ],
        ),
    ]
